function [] = visPieChart(optStruct,ax)

%unpack
S = optStruct.output.min;
opt = optStruct.opt;
loc = optStruct.loc;
c = optStruct.c;

%set chart specs
if optStruct.pm == 1 %wind
    PA = [S.kWcost S.Icost S.Scost S.battencl ...
        S.Pmtrl S.Panchor S.Pline S.Pinst S.battreplace S.turbrepair ...
        S.vesselcost];
    per = PA./1000;
    labl = {
        ['Turbine ($' num2str(round(per(1),2)) 'k)' ]; ...
        ['Turbine Installation ($' num2str(round(per(2),2)) 'k)' ]; ...
        ['Battery ($' num2str(round(per(3),2)) 'k)' ]; ... 
        ['Battery Enclosure ($' num2str(round(per(4),2)) 'k)' ]; ...               
        ['Platform Material ($' num2str(round(per(5),2)) 'k)' ]; ...
        
        ['Platform Installation ($' num2str(round(per(8),2)) 'k)' ]; ...
        ['Battery Replacement ($' num2str(round(per(9),2)) 'k)' ]; ...
        ['Turbine Repair ($' num2str(round(per(10),2)) 'k)' ]; ...
        ['Vessel Operations ($' num2str(round(per(11),2)) 'k)' ]};
    CapN = 8;
    OpN = 3;
    titl = {['Wind, ' char(loc) ', ' ... 
        char(opt.usecases(c)) ', total cost: $' ...
        num2str(round(S.cost,0)) ],''};
elseif optStruct.pm == 2 %inso
    PA = [S.Mcost S.Icost S.Ecost S.Strcost S.Scost S.battencl ...
        S.Pmtrl S.Panchor S.Pline S.Pinst S.battreplace S.vesselcost];
    per = PA./1000;
    labl = { ...
        ['PV Modules ($' num2str(round(per(1),2)) 'k)' ]; ...
        ['PV Insallation ($' num2str(round(per(2),2)) 'k)' ]; ...
        ['PV Electrical ($' num2str(round(per(3),2)) 'k)' ]; ...
        ['PV Structural ($' num2str(round(per(4),2)) 'k)' ]; ...
        ['Battery ($' num2str(round(per(5),2)) 'k)' ]; ... 
        ['Battery Enclosure ($' num2str(round(per(6),2)) 'k)' ]; ...
        ['Platform Material ($' num2str(round(per(7),2)) 'k)' ]; ...
        ['Anchor ($' num2str(round(per(8),2)) 'k)' ]; ...
        ['Mooring Line ($' num2str(round(per(9),2)) 'k)' ]; ...        
        ['Platform Installation ($' num2str(round(per(10),2)) 'k)' ]; ...
        ['Battery Replacement ($' num2str(round(per(11),2)) 'k)' ]; ...
        ['Vessel Operations ($' num2str(round(per(12),2)) 'k)' ]};
    CapN = 10;
    OpN = 2;
    titl = {['Solar, ' char(loc) ', ' ... 
        char(opt.usecases(c)) ', total cost: $' ...
        num2str(round(S.cost,0)) ],''};
elseif optStruct.pm == 3 %wave
    PA = [S.kWcost S.Icost S.Scost S.battencl S.Pinst ...
        S.Pmtrl S.Pmoor S.battreplace S.wecrepair S.vesselcost];
    per = PA./1000;
    labl = {
        ['WEC ($' num2str(round(per(1),2)) 'k)' ]; ...
        ['WEC Installation ($' num2str(round(per(2),2)) 'k)' ]; ...
        ['Battery ($' num2str(round(per(3),2)) 'k)' ]; ... 
        ['Battery Enclosure ($' num2str(round(per(4),2)) 'k)' ]; ...                
        ['Platform Installation ($' num2str(round(per(5),2)) 'k)' ]; ...        
        ['Platform Material ($' num2str(round(per(6),2)) 'k)' ]; ...
        ['Mooring ($' num2str(round(per(7),2)) 'k)' ]; ...
        ['Battery Replacement ($' num2str(round(per(8),2)) 'k)' ]; ...
        ['WEC Repair ($' num2str(round(per(9),2)) 'k)' ]; ...
        ['Vessel Operations ($' num2str(round(per(10),2)) 'k)' ]};
    CapN = 7;
    OpN = 3;
    titl = {['Wave, ' char(opt.wavescens(optStruct.econ.wave.scen)) ... 
        ', ' char(opt.locations(loc)) ', ' char(opt.usecases(c)) ...
        ', total cost: $' num2str(round(S.cost,0)) ],''};
elseif optStruct.pm == 4 %diesel
    PA = [S.kWcost S.genencl S.Scost S.battencl ...
        S.Pmtrl S.Panchor S.Pline S.Pinst S.fuel S.battreplace ...
        S.genrepair S.vesselcost];
    per = PA./1000;
    labl = {
        ['Generator ($' num2str(round(per(1),2)) 'k)' ]; ...
        ['Generator Enclosure ($' num2str(round(per(2),2)) 'k)' ]; ...                
        ['Battery ($' num2str(round(per(3),2)) 'k)' ]; ... 
        ['Battery Enclosure ($' num2str(round(per(4),2)) 'k)' ]; ...                                
        ['Platform Material ($' num2str(round(per(5),2)) 'k)' ]; ...
        ['Anchor ($' num2str(round(per(6),2)) 'k)' ]; ...
        ['Mooring Line ($' num2str(round(per(7),2)) 'k)' ]; ...
        ['Platform Installation ($' num2str(round(per(8),2)) 'k)' ]; ...
        ['Diesel Fuel ($' num2str(round(per(9),2)) 'k)' ]; ...
        ['Battery Replacement ($' num2str(round(per(10),2)) 'k)' ]; ...
        ['Generator Repair ($' num2str(round(per(11),2)) 'k)' ]; ...
        ['Vessel Operations ($' num2str(round(per(12),2)) 'k)' ]};
    CapN = 8;
    OpN = 4;
    titl = {['Diesel, ' char(loc) ', ' ... 
        char(opt.usecases(c)) ', total cost: $' ...
        num2str(round(S.cost,0)) ],''};
end

OpN = OpN - length(find(PA == 0)); %remove nonexistent operational costs

CapCol_all = brewermap(15,'reds');
OpCol_all = brewermap(10,'blues');
CapCol = CapCol_all(end-CapN+1:end,:);
OpCol = OpCol_all(end-OpN+1:end,:);

if exist('ax','var')
    p = pie(ax,PA);
else
    figure
    p = pie(PA);
end
legend(labl,'location','eastoutside')
colormap(gca,[CapCol;OpCol]);
dir = [0 0 1];
rotate(p,dir,180)
delete(findobj(p,'Type','text')) %remove percentage labels
title(titl);
% for i = 1:CapN
%     t = p(2*i);
%     t.BackgroundColor = CapCol(i,:);
%     t.Color = 'white';
% end
% for i = 1:OpN
%     t = p((CapN+i)*2);
%     t.BackgroundColor = OpCol(i,:);
%     t.Color = 'white';    
% end
set(gcf,'color','w');

end

