clc, close all, clear all
%set(0,'defaulttextinterpreter','none')
set(0,'defaulttextinterpreter','latex')
set(0,'DefaultTextFontname', 'helvetica')
set(0,'DefaultAxesFontName', 'helvetica')

%load data
load('struct1m_opt')
load('struct2m_opt')
load('struct3m_opt')
load('struct4m_opt')
load('struct5m_opt')
load('struct6m_opt')

%constants
rho = 1020; %[kg/m^3]
g = 9.81;   %[m/s^2]
lw1 = 3;
lw2 = .8;

%extract Tps and Hs
Tp_1 = unique(struct1m_opt.T);
Tp_2 = unique(struct2m_opt.T);
Tp_3 = unique(struct3m_opt.T);
Tp_4 = unique(struct4m_opt.T);
Tp_5 = unique(struct5m_opt.T);
Tp_6 = unique(struct6m_opt.T);
Hs_1 = unique(struct1m_opt.H);
Hs_2 = unique(struct2m_opt.H);
Hs_3 = unique(struct3m_opt.H);
Hs_4 = unique(struct4m_opt.H);
Hs_5 = unique(struct5m_opt.H);
Hs_6 = unique(struct6m_opt.H);

%set discretization
Tp_res = 1000;
Tp_all = zeros(Tp_res,6);
Tp_all(:,1) = linspace(min(Tp_1),max(Tp_1),Tp_res);
Tp_all(:,2) = linspace(min(Tp_2),max(Tp_2),Tp_res);
Tp_all(:,3) = linspace(min(Tp_3),max(Tp_3),Tp_res);
Tp_all(:,4) = linspace(min(Tp_4),max(Tp_4),Tp_res);
Tp_all(:,5) = linspace(min(Tp_5),max(Tp_5),Tp_res);
Tp_all(:,6) = linspace(min(Tp_6),max(Tp_6),Tp_res);

%preallocate
cwr_int = zeros(2,Tp_res,6);

%spline interpolate cwr at max and min Hs onto finely resolved Tp
cwr_int(1,:,1) = interp1(Tp_1, ...
    struct1m_opt.mat(1,:)'./ ...
    ((1/(64*pi))*rho*g^2*Hs_1(1)^2.*Tp_1.*struct1m_opt.B), ...
    linspace(min(Tp_1),max(Tp_1),Tp_res),'spline');
cwr_int(2,:,1) = interp1(Tp_1, ...
    struct1m_opt.mat(end,:)'./ ...
    ((1/(64*pi))*rho*g^2*Hs_1(end)^2.*Tp_1.*struct1m_opt.B), ...
    linspace(min(Tp_1),max(Tp_1),Tp_res),'spline');
cwr_int(1,:,2) = interp1(Tp_2, ...
    struct2m_opt.mat(1,:)'./ ...
    ((1/(64*pi))*rho*g^2*Hs_2(1)^2.*Tp_2.*struct2m_opt.B), ...
    linspace(min(Tp_2),max(Tp_2),Tp_res),'spline');
cwr_int(2,:,2) = interp1(Tp_2, ...
    struct2m_opt.mat(end,:)'./ ...
    ((1/(64*pi))*rho*g^2*Hs_2(end)^2.*Tp_2.*struct2m_opt.B), ...
    linspace(min(Tp_2),max(Tp_2),Tp_res),'spline');
cwr_int(1,:,3) = interp1(Tp_3, ...
    struct3m_opt.mat(1,:)'./ ...
    ((1/(64*pi))*rho*g^2*Hs_3(1)^2.*Tp_3.*struct3m_opt.B), ...
    linspace(min(Tp_3),max(Tp_3),Tp_res),'spline');
cwr_int(2,:,3) = interp1(Tp_3, ...
    struct3m_opt.mat(end,:)'./ ...
    ((1/(64*pi))*rho*g^2*Hs_3(end)^2.*Tp_3.*struct3m_opt.B), ...
    linspace(min(Tp_3),max(Tp_3),Tp_res),'spline');
cwr_int(1,:,4) = interp1(Tp_4, ...
    struct4m_opt.mat(1,:)'./ ...
    ((1/(64*pi))*rho*g^2*Hs_3(1)^2.*Tp_4.*struct4m_opt.B), ...
    linspace(min(Tp_4),max(Tp_4),Tp_res),'spline');
cwr_int(2,:,4) = interp1(Tp_4, ...
    struct4m_opt.mat(end,:)'./ ...
    ((1/(64*pi))*rho*g^2*Hs_4(end)^2.*Tp_4.*struct4m_opt.B), ...
    linspace(min(Tp_4),max(Tp_4),Tp_res),'spline');
cwr_int(1,:,5) = interp1(Tp_5, ...
    struct5m_opt.mat(1,:)'./ ...
    ((1/(64*pi))*rho*g^2*Hs_5(1)^2.*Tp_5.*struct5m_opt.B), ...
    linspace(min(Tp_5),max(Tp_5),Tp_res),'spline');
cwr_int(2,:,5) = interp1(Tp_5, ...
    struct5m_opt.mat(end,:)'./ ...
    ((1/(64*pi))*rho*g^2*Hs_5(end)^2.*Tp_5.*struct5m_opt.B), ...
    linspace(min(Tp_5),max(Tp_5),Tp_res),'spline');
cwr_int(1,:,6) = interp1(Tp_6, ...
    struct6m_opt.mat(1,:)'./ ...
    ((1/(64*pi))*rho*g^2*Hs_6(1)^2.*Tp_6.*struct6m_opt.B), ...
    linspace(min(Tp_6),max(Tp_6),Tp_res),'spline');
cwr_int(2,:,6) = interp1(Tp_6, ...
    struct6m_opt.mat(end,:)'./ ...
    ((1/(64*pi))*rho*g^2*Hs_6(end)^2.*Tp_6.*struct6m_opt.B), ...
    linspace(min(Tp_6),max(Tp_6),Tp_res),'spline');

%colors
c = 5;
col1 = brewermap(10,'oranges'); col(1,:) = col1(c,:);
col2 = brewermap(10,'reds'); col(2,:) = col2(c,:);
col3 = brewermap(10,'greens'); col(3,:) = col3(c,:);
col4 = brewermap(10,'blues'); col(4,:) = col4(c,:);
col5 = brewermap(10,'purples'); col(5,:) = col5(c,:);
col6 = brewermap(10,'greys'); col(6,:) = col6(c,:);

figure 
for i = 1:size(cwr_int,3)
    a(i,:) = area(Tp_all(:,i)', ...
        [cwr_int(2,:,i);cwr_int(1,:,i)-cwr_int(2,:,i)]');
    hold on
    a(i,2).FaceColor = col(i,:);
    a(i,2).FaceAlpha = 0.4;
    a(i,1).FaceAlpha = 0;
end
a(1,1).EdgeColor = 'none';

ylabel('CWR')
xlabel('Tp [s]')
hYLabel = get(gca,'YLabel');
set(hYLabel,'rotation',0,'VerticalAlignment','middle', ... 
    'HorizontalAlignment','right')
xlim([0 max([Tp_1 ; Tp_2 ; Tp_3 ; Tp_4 ; Tp_5 ; Tp_6])-4])
legend([a(1,2) a(2,2) a(3,2) a(4,2) a(5,2) a(6,2)], ...
    '1 m RM3 WEC','2 m RM3 WEC','3 m RM3 WEC','4 m RM3 WEC', ...
    '5 m RM3 WEC','6 m RM3 WEC','Location','best')
grid on
set(gca,'FontSize',13)

set(gcf, 'Position', [100, 100, 1150, 450])

